version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ad-dashboard-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: ad-dashboard-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: ad-dashboard-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
